# Generated by Django 5.1.2 on 2024-11-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerente',
            name='cargo',
            field=models.CharField(default='Sem cargo', max_length=20),
        ),
        migrations.AddField(
            model_name='gerente',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14),
        ),
        migrations.AddField(
            model_name='gerente',
            name='data_nascencia',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='gerente',
            name='genero',
            field=models.CharField(default='Sem genero', max_length=20),
        ),
        migrations.AddField(
            model_name='gerente',
            name='pais',
            field=models.CharField(default='Brasil', max_length=50),
        ),
        migrations.AddField(
            model_name='gerente',
            name='telefone',
            field=models.CharField(default='(00) 0000-0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='cidade',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='estado',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
