# Generated by Django 5.1.2 on 2024-11-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_gerente_cargo_gerente_cpf_gerente_data_nascencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerente',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
