# Generated by Django 5.1.2 on 2024-11-02 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_gerente_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gerente',
            old_name='data_nascencia',
            new_name='data_nascimento',
        ),
    ]
